# Generated by Django 5.0.2 on 2024-06-03 10:49

import common.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'webp', 'mpeg'])], verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phone_number', models.CharField(max_length=20, validators=[common.utils.validate_phone_number], verbose_name='Main Phone Number')),
                ('main_email_address', models.EmailField(max_length=254, verbose_name='Main Phone Address')),
                ('main_text', models.TextField(verbose_name='main text')),
                ('main_delivery_text', models.TextField(verbose_name='main delivery text')),
                ('main_banner_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_banner_image', to='common.media', verbose_name='Main Banner Image')),
                ('main_bottom_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_bottom_image', to='common.media', verbose_name='Main Bottom Image')),
            ],
            options={
                'verbose_name': 'Common Settings',
                'verbose_name_plural': 'Common Settings',
            },
        ),
    ]
